### PR TITLE
Spotify card updated

### PR DESCRIPTION
**Pull request by MG-LSJ**
- Bg color is the dominant color (instead of the middle pixel)
- Black/ white text color based on bg luminance
- Progress bar

### CODE REVIEW

**Comment by MG-LSJ** [comment]
image

**Comment by MG-LSJ** [comment]
image

**Comment by MG-LSJ** [comment]
image
bar thickness adjusted

**Comment by adam757521** [comment]
Please remove spotify_template from assets, as it is not used.
Please reformat the code using black.

**Comment by adam757521** [comment]
Amazing work, thank you.

**Pull request merged**
